name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  # backend_testing:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v4
  #       with:
  #         go-version: 1.18
  #     - uses: actions/checkout@v3
  #     - name: Building docker containers using docker-compose
  #       run: GO_MOD=go.mod docker-compose up -d --build
  #     - name: Golang Tests
  #       run: go test ./...
  #       working-directory: ./backend
  frontend_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: type check
        run: cd frontend && npm install && npm run types
      - name: react tests
        run: cd frontend && npm test
