name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  crud_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Linting
        run: |
          cd frontend
          npm run lint
      - name: React tests
        run: |
          cd frontend
          npm test

  frontend_testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Linting
        run: |
          cd frontend
          npm run lint
      - name: React tests
        run: |
          cd frontend
          npm test