name: Deploy Firebase Functions

on:
  push:
    branches:
      - brian2w/firebase-functions-auto-deploy-on-push-to-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Install dependencies
        run: |
          cd functions
          pip install -r requirements.txt

      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          firebase use --add socialsports-44162
          firebase deploy --only functions --token "$FIREBASE_TOKEN"
