name: Deploy Firebase Functions

on:
  push:
    branches:
      - brian2w/firebase-functions-auto-deploy-on-push-to-master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Create SA key
        run: echo '${{ secrets.GCP_SA_DEPLOY_KEY }}' > $HOME/gcloud.json

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # TODO: make it work for both environments
      - name: Decode and save functions_key.json
        working-directory: functions
        run: |
          echo ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY_DEV }} | base64 -d > ./functions_key.json

      - name: Deploy Cloud Functions
        working-directory: functions
        env:
          GOOGLE_APPLICATION_CREDENTIALS: $GITHUB_WORKSPACE/functions/functions_key.json
        run: |
          python3.12 -m venv venv
          . "$GITHUB_WORKSPACE/functions/venv/bin/activate" && python3.12 -m pip install -r requirements.txt
          firebase deploy --only functions --debug --project socialsports-44162

      # - name: Deploy to Firebase
      #   env:
      #     FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
      #   run: |
      #     firebase use --add socialsports-44162
      #     firebase deploy --only functions --token "$FIREBASE_TOKEN"
