name: CI

on:
  push:
    branches:
      - master

env:
  set_dev_env_variables: |
    cd frontend
    touch .env
    echo FIREBASE_DEV_API_KEY=${{ secrets.FIREBASE_DEV_API_KEY }} >> .env
    echo FIREBASE_DEV_AUTH_DOMAIN=${{ secrets.FIREBASE_DEV_AUTH_DOMAIN }} >> .env
    echo FIREBASE_DEV_DATABASE_URL=${{ secrets.FIREBASE_DEV_DATABASE_URL }} >> .env
    echo FIREBASE_DEV_PROJECT_ID=${{ secrets.FIREBASE_DEV_PROJECT_ID }} >> .env
    echo FIREBASE_DEV_STORAGE_BUCKET=${{ secrets.FIREBASE_DEV_STORAGE_BUCKET }} >> .env
    echo FIREBASE_DEV_MESSAGING_SENDER_ID=${{ secrets.FIREBASE_DEV_MESSAGING_SENDER_ID }} >> .env
    echo FIREBASE_DEV_APP_ID=${{ secrets.FIREBASE_DEV_APP_ID }} >> .env
    echo FIREBASE_DEV_MEASUREMENT_ID=${{ secrets.FIREBASE_DEV_MEASUREMENT_ID }} >> .env
    echo FIREBASE_SERIVCE_ACCOUNT_JSON=${{ secrets.FIREBASE_SERVICE_ACCOUNT_JSON }} >> .env

jobs:
  frontend_testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: create env file
        run: ${{ env.set_dev_env_variables }}
      - name: type check
        run: cd frontend && npm install
      - name: linting
        run: cd frontend && npm run lint
      - name: test building
        run: cd frontend && npm run build
      - name: react tests
        run: cd frontend && npm test
  configure_firebase:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - uses: "actions/checkout@v4"

      - id: "auth"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ env.FIREBASE_SERIVCE_ACCOUNT_JSON }}"

      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "get_stripe_checkout_url_by_event_id"
          runtime: "python310"
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "stripe_webhook_checkout_fulfilment"
          runtime: "python310"
      - id: "deploy"
        uses: "google-github-actions/deploy-cloud-functions@v2"
        with:
          name: "create_stripe_standard_account"
          runtime: "python310"
